[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
PROPAGATE_EXCEPTIONS = true
LOG_LEVEL = 'INFO'

API_DEFAULT_PAGE_SIZE = 10
API_MAX_PAGE_SIZE = 50

[development]

SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:@localhost:5432/call_billing'

[product]
SQLALCHEMY_DATABASE_URI = 'postgresql://admin:admin123@postgresql:5432/call_billing'

[testing]

SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:@localhost:5432/call_billing_test'